### PR TITLE
Migrate from deprecated LOC subject ID

### PR DESCRIPTION
**Pull request by bentley**
Reading the Library of Congress [Subject Headings Manual](https://www.loc.gov/aba/publications/FreeSHM/freeshm.html), I learned (in [H 405](https://www.loc.gov/aba/publications/FreeSHM/H0405.pdf)) that the Library of Congress keeps names‐as‐subjects and things‐as‐subjects under sister hierarchies, in the Name Authority file and the Subject Authority file respectively. As a rule, subjects that exist in the name file are removed from the subjects list, and new subjects will be put in one list or the other, but not both.

I made a list of the top‐level subjects in the corpus and picked out all (44) that were obvious names, whether of people, expeditions, places, or characters. Sure enough, all had entries in the Library of Congress name file, and sure enough, all were marked with unknown term IDs in the repos, except for this one, marked with a subject ID that’s since been [deprecated in favor of its name ID](https://id.loc.gov/authorities/subjects/sh88004835.html).

Full list of the others, all of which have exact matches in the LOC name file:

- Adams, Henry, 1838-1918
- Addams, Jane, 1860-1935
- Arnold, Thomas, 1795-1842
- Babbage, Charles, 1791-1871
- Barnum, P. T. (Phineas Taylor), 1810-1891
- Black Hawk, Sauk chief, 1767-1838
- British Antarctic ("Terra Nova") Expedition (1910-1913)
- Brown, John, 1800-1859
- Buffalo Bill, 1846-1917
- Bunyan, John, 1628-1688
- Burke, Edmund, 1729-1797. Reflections on the revolution in France
- Chesterton, G. K. (Gilbert Keith), 1874-1936
- De Quincey, Thomas, 1785-1859
- Douglass, Frederick, 1818-1895
- Equiano, Olaudah, 1745-1797
- Franklin, Benjamin, 1706-1790
- Goldman, Emma, 1869-1940
- Gordon, Charles George, 1833-1885
- Grant, Ulysses S. (Ulysses Simpson), 1822-1885
- Henson, Matthew Alexander, 1866-1955
- Imperial Trans-Antarctic Expedition (1914-1917)
- Jacobs, Harriet A. (Harriet Ann), 1813-1897
- Keller, Helen, 1880-1968
- Manning, Henry Edward, 1808-1892
- Mill, John Stuart, 1806-1873
- Muir, John, 1838-1914
- Nightingale, Florence, 1820-1910
- Northup, Solomon, 1808-1863?
- Poe, Edgar Allan, 1809-1849
- Roosevelt, Theodore, 1858-1919
- Shevchenko, Taras, 1814-1861
- Steele, Richard, Sir, 1672-1729
- Strindberg, August, 1849-1912
- Sugimoto, Etsuko, 1873-1950
- Tagore, Rabindranath, 1861-1941
- Tombstone (Ariz.)
- Tuskegee Institute
- Twain, Mark, 1835-1910
- Victoria, Queen of Great Britain, 1819-1901
- Voltaire, 1694-1778. Candide
- Washington, Booker T., 1856-1915
- Zitkala-Sa, 1876-1938

### CODE REVIEW

**Comment by acabal** [comment]
Finding the LoC subjects is done by `se create-draft`. If we also have to look at the names file, then should this be part of `se create-draft` too? Otherwise we're going to continue creating drafts with the wrong information.

If that's the case, we should update create-draft first, and then once we bump the version of the toolset we can go back and update the corpus. That way, we don't update it once, and then accept more ebooks that have errors in them afterwards.

**Comment by bentley** [comment]
Yes, that makes sense.

**Comment by acabal** [comment]
@robinwhittleton are you interested in seeing if you can add this to create-draft before the next toolset release? Shouldn't be too hard, basically the same code as we already have to search for LoC subjects. 

@bentley are you able to update the rest of the corpus to fix the ones you found?

**Comment by bentley** [comment]
Yes, I can update the headings in the corpus.

**Comment by acabal** [comment]
On further thought, this now begs the question... should we be *updating* these LoC subject headings, or *removing* them?

If LoC doens't use subject headings for people any more, then how valid is PG's information to begin with? Would we find the same data at LoC today as we have in this old PG source?

If I search for Horton's translation of Nibelungenlied on LoC, I get this result https://lccn.loc.gov/12037283 which doesn't list any subject headings at all. (Though it does list related names which I don't think is the same.)

That leads to the question of how PG finds their LoC subject headings to begin with. Do they make them up? Take them from some source that I don't know about?

Then, if we're updating these old LCSH headings to be NACOAF headings, then we should also change the "authority" of them in the metadata. But if I can't find a real LoC catalog entry listing NACOAF headings as LCSH headings, then should we be doing this at all?

Maybe we should answer these questions before we start making any updates.

**Comment by bentley** [comment]
> If I search for Horton's translation of Nibelungenlied on LoC, I get this result https://lccn.loc.gov/12037283 which doesn't list any subject headings at all.… That leads to the question of how PG finds their LoC subject headings to begin with. Do they make them up?

PG certainly uses LOC as a source for subjects sometimes. Multiple LOC book entries’ subjects match those of the SE book (and PG) perfectly. ([Example](https://id.loc.gov/resources/works/13165260.html), [example](https://id.loc.gov/resources/works/15582882.html).) PG adds them after some delay (“[The subject headings are usually added to new eBooks within a few weeks of their publication by Project Gutenberg](https://www.gutenberg.org/help/bibliographic_record.html)”), implying the process is not automatic like SE, so they probably use other sources or catalog manually in cases where LOC does not have a good list.

>On further thought, this now begs the question... should we be *updating* these LoC subject headings, or *removing* them?

Subjects that LOC has replaced with names? Updating, for sure. Because:

> But if I can't find a real LoC catalog entry listing NACOAF headings as LCSH headings, then should we be doing this at all?

There are such entries ([example](https://id.loc.gov/resources/works/13165260.html)).

**Comment by robinwhittleton** [comment]
Happy to make changes of course, but I’m not sure I really understand what the expected change here is. Basically, if we get an Unknown for a subject to try it with the name list instead?

**Comment by acabal** [comment]
Yes, exactly. We'd search for a subject heading first. If it doesn't exist, then search the name file. If *that* doesn't exist, then it really is `unknown`.

OK, if we're replacing those subject headings then what does the authority become? Is it still LCSH, or is it now NACOAF?

**Comment by bentley** [comment]
It seems like there’s a decent case that since the IDs don’t conflict and LOC uses them interchangeably in subject fields, that they’re the same kind of identifier. And since EPUB 3.2 reserves an authority ID for LCSH, it seems likely that more clients will be able to understand names marked under the reserved LCSH authority than names marked up under a non‐reserved authority string like NACOAF.

That said, EPUB 3.3 [purposely drops the reserved authorities list](https://www.w3.org/TR/epub-33/#authority), so I don’t feel strongly against marking them up with NACOAF either.

**Comment by acabal** [comment]
OK. Let's keep them as LCSH then. Since the different types of identifiers start with different letters, it'd be easy enough to adjust later if we change our minds.

So, this PR is good and I'll merge it. Can you update the rest in the corpus?

@robinwhittleton if you're interested, can you work on updating create-draft to check the name file as described above? If you don't have time that's OK, I'll put it on my to do list.

**Comment by robinwhittleton** [comment]
It’s not going to be top of my priorities, but I’ll give it a go. I’ll file an issue against tools, but please amend if you think that I’ve misunderstood.

**Pull request merged**
